// Baza de date cu cărți pentru Pictomania.
// Fiecare "carte" este o temă cu exact 7 cuvinte în limba română.
// Cuvintele dintr-o carte sunt înrudite (aceeași categorie) dar distincte,
// astfel încât să poată fi desenate individual, dar să fie ușor de confundat
// între ele — exact ce cere un joc bun de Pictomania.

const CARDS = {
  usor: [
    { tema: "Animale de fermă", cuvinte: ["Vacă", "Cal", "Porc", "Oaie", "Găină", "Rață", "Capră"] },
    { tema: "Animale sălbatice", cuvinte: ["Leu", "Elefant", "Urs", "Lup", "Vulpe", "Cerb", "Iepure"] },
    { tema: "Fructe", cuvinte: ["Măr", "Banană", "Pară", "Cireșe", "Căpșună", "Portocală", "Struguri"] },
    { tema: "Legume", cuvinte: ["Morcov", "Roșie", "Cartof", "Ceapă", "Ardei", "Castravete", "Varză"] },
    { tema: "Insecte", cuvinte: ["Fluture", "Albină", "Furnică", "Gândac", "Păianjen", "Muscă", "Buburuză"] },
    { tema: "Păsări", cuvinte: ["Vrabie", "Bufniță", "Pescăruș", "Cioară", "Porumbel", "Barză", "Papagal"] },
    { tema: "Vehicule", cuvinte: ["Mașină", "Autobuz", "Tren", "Bicicletă", "Avion", "Vapor", "Camion"] },
    { tema: "Îmbrăcăminte", cuvinte: ["Cămașă", "Pantaloni", "Rochie", "Pălărie", "Pantofi", "Mănuși", "Fular"] },
    { tema: "În bucătărie", cuvinte: ["Farfurie", "Furculiță", "Cuțit", "Lingură", "Oală", "Pahar", "Tigaie"] },
    { tema: "Mobilă", cuvinte: ["Scaun", "Masă", "Pat", "Dulap", "Canapea", "Raft", "Oglindă"] },
    { tema: "Corpul uman", cuvinte: ["Mână", "Picior", "Ochi", "Nas", "Ureche", "Gură", "Păr"] },
    { tema: "Jucării", cuvinte: ["Minge", "Păpușă", "Balon", "Zmeu", "Trotinetă", "Cub", "Ursuleț"] },
    { tema: "În baie", cuvinte: ["Periuță", "Prosop", "Săpun", "Duș", "Cadă", "Oglindă", "Pieptene"] },
    { tema: "Vremea", cuvinte: ["Soare", "Nor", "Ploaie", "Fulger", "Zăpadă", "Curcubeu", "Vânt"] },
    { tema: "Obiecte de sport", cuvinte: ["Minge", "Rachetă", "Schiuri", "Patine", "Coardă", "Haltere", "Fluier"] },
    { tema: "Instrumente muzicale", cuvinte: ["Chitară", "Pian", "Tobă", "Vioară", "Trompetă", "Flaut", "Acordeon"] },
    { tema: "Unelte", cuvinte: ["Ciocan", "Șurubelniță", "Fierăstrău", "Cheie", "Cui", "Foarfece", "Ruletă"] },
    { tema: "Deserturi", cuvinte: ["Prăjitură", "Înghețată", "Ciocolată", "Gogoașă", "Tort", "Bomboană", "Clătită"] },
    { tema: "Mâncare", cuvinte: ["Pizza", "Hamburger", "Cârnat", "Pâine", "Brânză", "Ou", "Supă"] },
    { tema: "Băuturi", cuvinte: ["Apă", "Cafea", "Ceai", "Suc", "Lapte", "Vin", "Limonadă"] },
    { tema: "Natura", cuvinte: ["Copac", "Floare", "Munte", "Râu", "Lac", "Piatră", "Iarbă"] },
    { tema: "Spațiu", cuvinte: ["Soare", "Lună", "Stea", "Planetă", "Rachetă", "Cometă", "Extraterestru"] },
    { tema: "Casa", cuvinte: ["Ușă", "Fereastră", "Acoperiș", "Scară", "Coș de fum", "Gard", "Poartă"] },
    { tema: "Rechizite școlare", cuvinte: ["Creion", "Caiet", "Gumă", "Riglă", "Foarfece", "Penar", "Ghiozdan"] },
    { tema: "Viețuitoare marine", cuvinte: ["Pește", "Rechin", "Meduză", "Crab", "Caracatiță", "Scoică", "Steluță de mare"] },
    { tema: "În grădină", cuvinte: ["Lopată", "Greblă", "Furtun", "Ghiveci", "Stropitoare", "Roabă", "Sămânță"] },
    { tema: "Electronice", cuvinte: ["Telefon", "Laptop", "Televizor", "Cameră foto", "Căști", "Mouse", "Tastatură"] },
    { tema: "Forme", cuvinte: ["Cerc", "Pătrat", "Triunghi", "Stea", "Inimă", "Romb", "Dreptunghi"] },
    { tema: "Animale de companie", cuvinte: ["Câine", "Pisică", "Hamster", "Papagal", "Broască țestoasă", "Iepure", "Peștișor"] },
    { tema: "Iarna", cuvinte: ["Om de zăpadă", "Sanie", "Patine", "Fulg de nea", "Țurțur", "Mănuși", "Căciulă"] },
  ],
  mediu: [
    { tema: "Meserii", cuvinte: ["Doctor", "Pompier", "Bucătar", "Polițist", "Profesor", "Pilot", "Fermier"] },
    { tema: "Profesii", cuvinte: ["Arhitect", "Avocat", "Chelner", "Mecanic", "Grădinar", "Croitor", "Frizer"] },
    { tema: "Emoții", cuvinte: ["Bucurie", "Tristețe", "Furie", "Frică", "Mirare", "Plictiseală", "Dragoste"] },
    { tema: "Sporturi", cuvinte: ["Fotbal", "Tenis", "Înot", "Box", "Schi", "Baschet", "Ciclism"] },
    { tema: "Personaje mitologice", cuvinte: ["Zeu", "Zână", "Vrăjitor", "Sirenă", "Dragon", "Uriaș", "Spiriduș"] },
    { tema: "Războinici din istorie", cuvinte: ["Cavaler", "Pirat", "Viking", "Samurai", "Cowboy", "Gladiator", "Arcaș"] },
    { tema: "Profesii artistice", cuvinte: ["Pictor", "Dansator", "Muzician", "Actor", "Sculptor", "Fotograf", "Clovn"] },
    { tema: "Clădiri", cuvinte: ["Biserică", "Castel", "Far", "Moară", "Zgârie-nori", "Pod", "Turn"] },
    { tema: "Locuri", cuvinte: ["Spital", "Școală", "Restaurant", "Bancă", "Teatru", "Bibliotecă", "Stadion"] },
    { tema: "Activități în timpul liber", cuvinte: ["Citit", "Pescuit", "Drumeție", "Pictură", "Dans", "Gătit", "Grădinărit"] },
    { tema: "Fenomene naturale", cuvinte: ["Cutremur", "Tornadă", "Erupție", "Inundație", "Avalanșă", "Tsunami", "Uragan"] },
    { tema: "Sărbători și evenimente", cuvinte: ["Crăciun", "Paște", "Aniversare", "Nuntă", "Halloween", "Revelion", "Carnaval"] },
    { tema: "Repere celebre", cuvinte: ["Piramidă", "Turnul Eiffel", "Statuia Libertății", "Colosseum", "Marele Zid", "Big Ben", "Taj Mahal"] },
    { tema: "Dinozauri", cuvinte: ["T-Rex", "Triceratops", "Velociraptor", "Brontozaur", "Pterodactil", "Stegozaur", "Diplodocus"] },
    { tema: "Unelte de artist", cuvinte: ["Pensulă", "Șevalet", "Paletă", "Cariocă", "Cerneală", "Pană de scris", "Spray"] },
    { tema: "Meserii curajoase", cuvinte: ["Scafandru", "Alpinist", "Dresor", "Cascador", "Miner", "Salvamar", "Astronaut"] },
    { tema: "Transport", cuvinte: ["Metrou", "Tramvai", "Taxi", "Feribot", "Teleferic", "Elicopter", "Submarin"] },
    { tema: "Animale exotice", cuvinte: ["Cangur", "Koala", "Panda", "Leneș", "Lamă", "Flamingo", "Tucan"] },
    { tema: "Reptile și amfibieni", cuvinte: ["Șarpe", "Crocodil", "Șopârlă", "Broască", "Cameleon", "Iguană", "Salamandră"] },
    { tema: "Acțiuni", cuvinte: ["A alerga", "A sări", "A dormi", "A mânca", "A citi", "A înota", "A cânta"] },
    { tema: "Acțiuni cu emoție", cuvinte: ["A plânge", "A râde", "A striga", "A îmbrățișa", "A cădea", "A împinge", "A arunca"] },
    { tema: "Obiecte magice", cuvinte: ["Baghetă", "Cazan", "Glob de cristal", "Covor zburător", "Lampă fermecată", "Poțiune", "Carte de vrăji"] },
    { tema: "La camping", cuvinte: ["Cort", "Foc de tabără", "Hartă", "Busolă", "Rucsac", "Lanternă", "Hamac"] },
    { tema: "Vreme extremă", cuvinte: ["Viscol", "Ceață", "Grindină", "Secetă", "Potop", "Îngheț", "Caniculă"] },
    { tema: "Muzică și spectacol", cuvinte: ["Rock", "Operă", "Balet", "Cor", "Fanfară", "Karaoke", "Concert"] },
    { tema: "Semne zodiacale", cuvinte: ["Berbec", "Taur", "Leu", "Pești", "Balanță", "Săgetător", "Scorpion"] },
    { tema: "Legume mai rare", cuvinte: ["Vânătă", "Dovleac", "Sparanghel", "Broccoli", "Ridiche", "Praz", "Sfeclă"] },
    { tema: "Condimente și arome", cuvinte: ["Sare", "Piper", "Scorțișoară", "Usturoi", "Busuioc", "Boia", "Mentă"] },
    { tema: "Mijloace de comunicare", cuvinte: ["Scrisoare", "Telegramă", "Radio", "Ziar", "Megafon", "Semafor", "Poștaș"] },
    { tema: "Personaje din povești", cuvinte: ["Scufița Roșie", "Cenușăreasa", "Făt-Frumos", "Baba Cloanța", "Zmeul", "Prințul", "Piticul"] },
  ],
};

if (typeof module !== "undefined") { module.exports = CARDS; }
