// Baza de date cu cărți pentru Pictomania.
// Fiecare "carte" este o temă cu exact 7 cuvinte în limba română.
// Cuvintele dintr-o carte sunt înrudite (aceeași categorie) dar distincte,
// astfel încât să poată fi desenate individual, dar să fie ușor de confundat
// între ele — exact ce cere un joc bun de Pictomania.
// ID-urile sunt permanente: nu le renumerota la reordonarea cărților.

const CARDS = {
  usor: [
    { id: "card-001", tema: "Animale de fermă", cuvinte: ["Vacă", "Cal", "Porc", "Oaie", "Găină", "Rață", "Capră"] },
    { id: "card-002", tema: "Animale sălbatice", cuvinte: ["Leu", "Elefant", "Urs", "Lup", "Vulpe", "Cerb", "Iepure"] },
    { id: "card-003", tema: "Fructe", cuvinte: ["Măr", "Banană", "Pară", "Cireșe", "Căpșună", "Portocală", "Struguri"] },
    { id: "card-004", tema: "Legume", cuvinte: ["Morcov", "Roșie", "Cartof", "Ceapă", "Ardei", "Castravete", "Varză"] },
    { id: "card-005", tema: "Insecte", cuvinte: ["Fluture", "Albină", "Furnică", "Gândac", "Păianjen", "Muscă", "Buburuză"] },
    { id: "card-006", tema: "Păsări", cuvinte: ["Vrabie", "Bufniță", "Pescăruș", "Cioară", "Porumbel", "Barză", "Papagal"] },
    { id: "card-007", tema: "Vehicule", cuvinte: ["Mașină", "Autobuz", "Tren", "Bicicletă", "Avion", "Vapor", "Camion"] },
    { id: "card-008", tema: "Îmbrăcăminte", cuvinte: ["Cămașă", "Pantaloni", "Rochie", "Pălărie", "Pantofi", "Mănuși", "Fular"] },
    { id: "card-009", tema: "În bucătărie", cuvinte: ["Farfurie", "Furculiță", "Cuțit", "Lingură", "Oală", "Pahar", "Tigaie"] },
    { id: "card-010", tema: "Mobilă", cuvinte: ["Scaun", "Masă", "Pat", "Dulap", "Canapea", "Raft", "Oglindă"] },
    { id: "card-011", tema: "Corpul uman", cuvinte: ["Mână", "Picior", "Ochi", "Nas", "Ureche", "Gură", "Păr"] },
    { id: "card-012", tema: "Jucării", cuvinte: ["Minge", "Păpușă", "Balon", "Zmeu", "Trotinetă", "Cub", "Ursuleț"] },
    { id: "card-013", tema: "În baie", cuvinte: ["Periuță", "Prosop", "Săpun", "Duș", "Cadă", "Oglindă", "Pieptene"] },
    { id: "card-014", tema: "Vremea", cuvinte: ["Soare", "Nor", "Ploaie", "Fulger", "Zăpadă", "Curcubeu", "Vânt"] },
    { id: "card-015", tema: "Obiecte de sport", cuvinte: ["Minge", "Rachetă", "Schiuri", "Patine", "Coardă", "Haltere", "Fluier"] },
    { id: "card-016", tema: "Instrumente muzicale", cuvinte: ["Chitară", "Pian", "Tobă", "Vioară", "Trompetă", "Flaut", "Acordeon"] },
    { id: "card-017", tema: "Unelte", cuvinte: ["Ciocan", "Șurubelniță", "Fierăstrău", "Cheie", "Cui", "Foarfece", "Ruletă"] },
    { id: "card-018", tema: "Deserturi", cuvinte: ["Prăjitură", "Înghețată", "Ciocolată", "Gogoașă", "Tort", "Bomboană", "Clătită"] },
    { id: "card-019", tema: "Mâncare", cuvinte: ["Pizza", "Hamburger", "Cârnat", "Pâine", "Brânză", "Ou", "Supă"] },
    { id: "card-020", tema: "Băuturi", cuvinte: ["Apă", "Cafea", "Ceai", "Suc", "Lapte", "Vin", "Limonadă"] },
    { id: "card-021", tema: "Natura", cuvinte: ["Copac", "Floare", "Munte", "Râu", "Lac", "Piatră", "Iarbă"] },
    { id: "card-022", tema: "Spațiu", cuvinte: ["Soare", "Lună", "Stea", "Planetă", "Rachetă", "Cometă", "Extraterestru"] },
    { id: "card-023", tema: "Casa", cuvinte: ["Ușă", "Fereastră", "Acoperiș", "Scară", "Coș de fum", "Gard", "Poartă"] },
    { id: "card-024", tema: "Rechizite școlare", cuvinte: ["Creion", "Caiet", "Gumă", "Riglă", "Foarfece", "Penar", "Ghiozdan"] },
    { id: "card-025", tema: "Viețuitoare marine", cuvinte: ["Pește", "Rechin", "Meduză", "Crab", "Caracatiță", "Scoică", "Steluță de mare"] },
    { id: "card-026", tema: "În grădină", cuvinte: ["Lopată", "Greblă", "Furtun", "Ghiveci", "Stropitoare", "Roabă", "Sămânță"] },
    { id: "card-027", tema: "Electronice", cuvinte: ["Telefon", "Laptop", "Televizor", "Cameră foto", "Căști", "Mouse", "Tastatură"] },
    { id: "card-028", tema: "Forme", cuvinte: ["Cerc", "Pătrat", "Triunghi", "Stea", "Inimă", "Romb", "Dreptunghi"] },
    { id: "card-029", tema: "Animale de companie", cuvinte: ["Câine", "Pisică", "Hamster", "Papagal", "Broască țestoasă", "Iepure", "Peștișor"] },
    { id: "card-030", tema: "Iarna", cuvinte: ["Om de zăpadă", "Sanie", "Patine", "Fulg de nea", "Țurțur", "Mănuși", "Căciulă"] },
    { id: "card-031", tema: "La circ", cuvinte: ["Clovn", "Acrobat", "Leu", "Elefant", "Trapez", "Cort", "Magician"] },
    { id: "card-032", tema: "Fructe exotice", cuvinte: ["Ananas", "Kiwi", "Mango", "Pepene", "Nucă de cocos", "Smochină", "Rodie"] },
    { id: "card-033", tema: "La plajă", cuvinte: ["Umbrelă", "Prosop", "Minge", "Castel de nisip", "Ochelari de soare", "Colac", "Scoică"] },
    { id: "card-034", tema: "Pe apă", cuvinte: ["Barcă", "Caiac", "Iaht", "Canoe", "Plută", "Submarin", "Jet-ski"] },
    { id: "card-035", tema: "Păsări de curte", cuvinte: ["Găină", "Cocoș", "Curcan", "Gâscă", "Rață", "Bibilică", "Pui"] },
    { id: "card-036", tema: "Animale de munte", cuvinte: ["Capră neagră", "Urs", "Cerb", "Vultur", "Marmotă", "Râs", "Mistreț"] },
    { id: "card-037", tema: "În oraș", cuvinte: ["Semafor", "Felinar", "Bancă", "Fântână", "Statuie", "Coș de gunoi", "Indicator"] },
    { id: "card-038", tema: "De scris și desenat", cuvinte: ["Creion", "Pix", "Stilou", "Cariocă", "Cretă", "Marker", "Radieră"] },
    { id: "card-039", tema: "Bijuterii și accesorii", cuvinte: ["Inel", "Colier", "Cercei", "Brățară", "Ceas", "Coroană", "Diademă"] },
    { id: "card-040", tema: "Fructe de pădure", cuvinte: ["Zmeură", "Mure", "Afine", "Coacăze", "Fragi", "Măceșe", "Alune"] },
    { id: "card-041", tema: "Dulciuri", cuvinte: ["Acadea", "Jeleu", "Gumă de mestecat", "Biscuit", "Napolitană", "Halva", "Turtă dulce"] },
    { id: "card-042", tema: "Micul dejun", cuvinte: ["Ou", "Corn", "Unt", "Gem", "Cereale", "Clătite", "Croissant"] },
    { id: "card-043", tema: "Legume rădăcinoase", cuvinte: ["Cartof", "Morcov", "Ceapă", "Usturoi", "Ridiche", "Țelină", "Sfeclă"] },
    { id: "card-044", tema: "Obiecte din clasă", cuvinte: ["Tablă", "Catalog", "Hartă", "Glob", "Bancă", "Cretă", "Burete"] },
    { id: "card-045", tema: "Jocuri de societate", cuvinte: ["Șah", "Table", "Cărți", "Zaruri", "Domino", "Puzzle", "Țintar"] },
    { id: "card-046", tema: "Electrocasnice", cuvinte: ["Frigider", "Aragaz", "Cuptor", "Blender", "Prăjitor de pâine", "Mixer", "Cântar"] },
    { id: "card-047", tema: "Haine de iarnă", cuvinte: ["Geacă", "Fular", "Căciulă", "Mănuși", "Cizme", "Pulover", "Ciorapi"] },
    { id: "card-048", tema: "Instrumente de percuție", cuvinte: ["Tobă", "Timpan", "Xilofon", "Maracas", "Trianglu", "Tamburină", "Gong"] },
    { id: "card-049", tema: "Animale mici de casă", cuvinte: ["Hamster", "Cobai", "Șoarece", "Canar", "Broască țestoasă", "Iepure", "Peștișor"] },
    { id: "card-050", tema: "De curățenie", cuvinte: ["Mătură", "Mop", "Găleată", "Aspirator", "Cârpă", "Burete", "Făraș"] },
  ],
  mediu: [
    { id: "card-051", tema: "Meserii", cuvinte: ["Doctor", "Pompier", "Bucătar", "Polițist", "Profesor", "Pilot", "Fermier"] },
    { id: "card-052", tema: "Profesii", cuvinte: ["Arhitect", "Avocat", "Chelner", "Mecanic", "Grădinar", "Croitor", "Frizer"] },
    { id: "card-053", tema: "Emoții", cuvinte: ["Bucurie", "Tristețe", "Furie", "Frică", "Mirare", "Plictiseală", "Dragoste"] },
    { id: "card-054", tema: "Sporturi", cuvinte: ["Fotbal", "Tenis", "Înot", "Box", "Schi", "Baschet", "Ciclism"] },
    { id: "card-055", tema: "Personaje mitologice", cuvinte: ["Zeu", "Zână", "Vrăjitor", "Sirenă", "Dragon", "Uriaș", "Spiriduș"] },
    { id: "card-056", tema: "Războinici din istorie", cuvinte: ["Cavaler", "Pirat", "Viking", "Samurai", "Cowboy", "Gladiator", "Arcaș"] },
    { id: "card-057", tema: "Profesii artistice", cuvinte: ["Pictor", "Dansator", "Muzician", "Actor", "Sculptor", "Fotograf", "Clovn"] },
    { id: "card-058", tema: "Clădiri", cuvinte: ["Biserică", "Castel", "Far", "Moară", "Zgârie-nori", "Pod", "Turn"] },
    { id: "card-059", tema: "Locuri", cuvinte: ["Spital", "Școală", "Restaurant", "Bancă", "Teatru", "Bibliotecă", "Stadion"] },
    { id: "card-060", tema: "Activități în timpul liber", cuvinte: ["Citit", "Pescuit", "Drumeție", "Pictură", "Dans", "Gătit", "Grădinărit"] },
    { id: "card-061", tema: "Fenomene naturale", cuvinte: ["Cutremur", "Tornadă", "Erupție", "Inundație", "Avalanșă", "Tsunami", "Uragan"] },
    { id: "card-062", tema: "Sărbători și evenimente", cuvinte: ["Crăciun", "Paște", "Aniversare", "Nuntă", "Halloween", "Revelion", "Carnaval"] },
    { id: "card-063", tema: "Repere celebre", cuvinte: ["Piramidă", "Turnul Eiffel", "Statuia Libertății", "Colosseum", "Marele Zid", "Big Ben", "Taj Mahal"] },
    { id: "card-064", tema: "Dinozauri", cuvinte: ["T-Rex", "Triceratops", "Velociraptor", "Brontozaur", "Pterodactil", "Stegozaur", "Diplodocus"] },
    { id: "card-065", tema: "Unelte de artist", cuvinte: ["Pensulă", "Șevalet", "Paletă", "Cariocă", "Cerneală", "Pană de scris", "Spray"] },
    { id: "card-066", tema: "Meserii curajoase", cuvinte: ["Scafandru", "Alpinist", "Dresor", "Cascador", "Miner", "Salvamar", "Astronaut"] },
    { id: "card-067", tema: "Transport", cuvinte: ["Metrou", "Tramvai", "Taxi", "Feribot", "Teleferic", "Elicopter", "Submarin"] },
    { id: "card-068", tema: "Animale exotice", cuvinte: ["Cangur", "Koala", "Panda", "Leneș", "Lamă", "Flamingo", "Tucan"] },
    { id: "card-069", tema: "Reptile și amfibieni", cuvinte: ["Șarpe", "Crocodil", "Șopârlă", "Broască", "Cameleon", "Iguană", "Salamandră"] },
    { id: "card-070", tema: "Acțiuni", cuvinte: ["A alerga", "A sări", "A dormi", "A mânca", "A citi", "A înota", "A cânta"] },
    { id: "card-071", tema: "Acțiuni cu emoție", cuvinte: ["A plânge", "A râde", "A striga", "A îmbrățișa", "A cădea", "A împinge", "A arunca"] },
    { id: "card-072", tema: "Obiecte magice", cuvinte: ["Baghetă", "Cazan", "Glob de cristal", "Covor zburător", "Lampă fermecată", "Poțiune", "Carte de vrăji"] },
    { id: "card-073", tema: "La camping", cuvinte: ["Cort", "Foc de tabără", "Hartă", "Busolă", "Rucsac", "Lanternă", "Hamac"] },
    { id: "card-074", tema: "Vreme extremă", cuvinte: ["Viscol", "Ceață", "Grindină", "Secetă", "Potop", "Îngheț", "Caniculă"] },
    { id: "card-075", tema: "Muzică și spectacol", cuvinte: ["Rock", "Operă", "Balet", "Cor", "Fanfară", "Karaoke", "Concert"] },
    { id: "card-076", tema: "Semne zodiacale", cuvinte: ["Berbec", "Taur", "Leu", "Pești", "Balanță", "Săgetător", "Scorpion"] },
    { id: "card-077", tema: "Legume mai rare", cuvinte: ["Vânătă", "Dovleac", "Sparanghel", "Broccoli", "Ridiche", "Praz", "Sfeclă"] },
    { id: "card-078", tema: "Condimente și arome", cuvinte: ["Sare", "Piper", "Scorțișoară", "Usturoi", "Busuioc", "Boia", "Mentă"] },
    { id: "card-079", tema: "Mijloace de comunicare", cuvinte: ["Scrisoare", "Telegramă", "Radio", "Ziar", "Megafon", "Semafor", "Poștaș"] },
    { id: "card-080", tema: "Personaje din povești", cuvinte: ["Scufița Roșie", "Cenușăreasa", "Făt-Frumos", "Baba Cloanța", "Zmeul", "Prințul", "Piticul"] },
    { id: "card-081", tema: "Sporturi de iarnă", cuvinte: ["Schi", "Snowboard", "Patinaj", "Hochei", "Sanie", "Biatlon", "Curling"] },
    { id: "card-082", tema: "Profesii din spital", cuvinte: ["Chirurg", "Asistentă", "Dentist", "Farmacist", "Veterinar", "Optician", "Kinetoterapeut"] },
    { id: "card-083", tema: "Meserii de demult", cuvinte: ["Fierar", "Cizmar", "Olar", "Țesător", "Morar", "Potcovar", "Coșar"] },
    { id: "card-084", tema: "Instrumente științifice", cuvinte: ["Microscop", "Telescop", "Busolă", "Termometru", "Lupă", "Eprubetă", "Cântar"] },
    { id: "card-085", tema: "Planete", cuvinte: ["Mercur", "Venus", "Marte", "Jupiter", "Saturn", "Uranus", "Neptun"] },
    { id: "card-086", tema: "Personaje SF", cuvinte: ["Robot", "Extraterestru", "Astronaut", "Cyborg", "Mutant", "Clonă", "Android"] },
    { id: "card-087", tema: "Stări sufletești", cuvinte: ["Curaj", "Gelozie", "Rușine", "Speranță", "Oboseală", "Entuziasm", "Nostalgie"] },
    { id: "card-088", tema: "Genuri de film", cuvinte: ["Comedie", "Groază", "Acțiune", "Romantic", "Western", "Animație", "Documentar"] },
    { id: "card-089", tema: "Dansuri", cuvinte: ["Vals", "Tango", "Balet", "Breakdance", "Salsa", "Hip-hop", "Horă"] },
    { id: "card-090", tema: "Superputeri", cuvinte: ["Zbor", "Invizibilitate", "Super-forță", "Teleportare", "Viteză", "Telepatie", "Rază laser"] },
    { id: "card-091", tema: "Materii școlare", cuvinte: ["Matematică", "Istorie", "Geografie", "Biologie", "Chimie", "Muzică", "Desen"] },
    { id: "card-092", tema: "Locuri de vacanță", cuvinte: ["Plajă", "Munte", "Deltă", "Insulă", "Deșert", "Junglă", "Peșteră"] },
    { id: "card-093", tema: "Construcții celebre", cuvinte: ["Pod", "Tunel", "Baraj", "Turn de apă", "Zgârie-nori", "Amfiteatru", "Far"] },
    { id: "card-094", tema: "Vehicule speciale", cuvinte: ["Ambulanță", "Mașină de pompieri", "Mașină de poliție", "Betonieră", "Macara", "Buldozer", "Tractor"] },
    { id: "card-095", tema: "Artiști de circ", cuvinte: ["Clovn", "Acrobat", "Magician", "Dresor", "Jongler", "Echilibrist", "Iluzionist"] },
    { id: "card-096", tema: "Anotimpuri și momente", cuvinte: ["Răsărit", "Amiază", "Apus", "Noapte", "Primăvară", "Vară", "Iarnă"] },
    { id: "card-097", tema: "Profesii creative", cuvinte: ["Fotograf", "Designer", "Regizor", "Scriitor", "Compozitor", "Animator", "Bloger"] },
    { id: "card-098", tema: "Animale preistorice", cuvinte: ["Mamut", "Tigru cu colți", "Dinozaur", "Pterodactil", "Rinocer lânos", "Dodo", "Megalodon"] },
    { id: "card-099", tema: "Simboluri", cuvinte: ["Inimă", "Stea", "Cruce", "Ancoră", "Coroană", "Fulger", "Trifoi"] },
    { id: "card-100", tema: "Meserii cu animale", cuvinte: ["Veterinar", "Cioban", "Apicultor", "Dresor", "Jocheu", "Pescar", "Crescător"] },
  ],
};

if (typeof module !== "undefined") { module.exports = CARDS; }
